language: python
python:
  - 3.6
install:
  - pip install -r requirements.txt
script:
  - make build
deploy:
  provider: pages
  fqdn: mindtrove.info
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  local-dir: _output
  verbose: true
  on:
    branch: master